services:
  python-telegram-bot:
    build: .
    image: "ghcr.io/oasisprotocol/demo-rofl-tgbot@sha256:4ebcd0c713a47286f86a2434acadf2d7199706589605e417a5958c0f23cc78cc"
    platform: linux/amd64
    environment:
      - TELEGRAM_API_TOKEN=${TELEGRAM_API_TOKEN}
      - TOKEN=${TOKEN}
